---
## installs and sets up Mariadb
- name: Install MariaDB package
  apt: name={{item}} state=latest
  with_items:
    - mariadb-server
    - python3-mysqldb

- name: Start MariaDB Service
  service: name=mysql state=started enabled=yes

- name: Create random password for root user
  command: php -r "echo md5(random_bytes(10));"
  register: mysql_root_password

# localhost needs to be the last item for idempotency
- name: Update mysql root password for all root accounts
  mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password.stdout }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Delete anonymous MySQL server user for server hostname
  action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"

- name: Delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"

- name: Remove the MySQL test database
  action: mysql_db db=test state=absent