---
# defaults file for logentries
logentries_packages: []
logentries_apt_repositories: []
logentries_apt_keys: []
logentries_account_key: ""
logentries_daemon_package: logentries-daemon
logentries_logs: []
logentries_service: logentries
logentries_repo_template: ""