---
- name: Add PHP repo
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP
  apt:
    name: "{{ item }}"
    state: present
    force: yes
    update_cache: yes
  with_items:
  - php7.1-cli
  - php7.1-common
  - php7.1-curl
  - php7.1-dev
  - php7.1-fpm
  - php7.1-gd
  - php7.1-mbstring
  - php7.1-mcrypt
  - php7.1-mysql
  - php7.1-opcache
  - php7.1-xml
  - php7.1-xmlrpc
  - php7.1-zip
  - php-redis

- name: Set PHP user
  lineinfile:
    dest: /etc/php/7.1/fpm/pool.d/www.conf
    regexp: "^user"
    line: "user = {{ remote_web_user }}"
    state: present
  notify: restart php

- name: Set PHP group
  lineinfile:
    dest: /etc/php/7.1/fpm/pool.d/www.conf
    regexp: "^group"
    line: "group = {{ remote_web_user }}"
    state: present
  notify: restart php

- name: Set PHP listen owner
  lineinfile:
    dest: /etc/php/7.1/fpm/pool.d/www.conf
    regexp: "^listen\\.owner"
    line: "listen.owner = {{ remote_web_user }}"
    state: present
  notify: restart php

- name: Set PHP listen group
  lineinfile:
    dest: /etc/php/7.1/fpm/pool.d/www.conf
    regexp: "^listen\\.group"
    line: "listen.group = {{ remote_web_user }}"
    state: present
  notify: restart php

- name: Set PHP upload max filesize
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: "^upload_max_filesize"
    line: "upload_max_filesize = 128M"
    state: present
  notify: reload php

- name: Set PHP post max filesize
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: "^post_max_size"
    line: "post_max_size = 128M"
    state: present
  notify: reload php